services:
  server:
    build: .
    image: shareit-server
    container_name: shareit-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit
      - TZ=UTC
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=UTC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit?timeZone=UTC
      - SPRING_JPA_PROPERTIES_JAKARTA_PERSISTENCE_JDBC_TIME_ZONE=UTC
      - LOGGING_LEVEL_ORG_HIBERNATE=DEBUG
      - LOGGING_LEVEL_ORG_POSTGRES=DEBUG

  db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_DB=shareit
      - TZ=UTC
      - PGTZ=UTC  # Устанавливаем часовой пояс для PostgreSQL
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10